AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito - homelabwithkevin

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.10

Parameters:
  Placeholder:
    Type: String
    Description: Used for minor updates.

  Domain:
    Type: String

  RedirectURL:
    Type: String

  CognitoHostedURL:
    Type: String

  ClientSecret:
    Type: String

# https://stackoverflow.com/questions/46619746/aws-cognito-how-to-create-pool-allowing-sign-up-with-email-address-using-clou
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      EmailConfiguration: 
        EmailSendingAccount: COGNITO_DEFAULT
      AutoVerifiedAttributes:
        - email
      AliasAttributes:
        - email
        - preferred_username
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 7

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref Domain

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Ref Domain

      # AuthSessionValidity: 3
      # AccessTokenValidity: 1
      # RefreshTokenValidity: 30
      # IdTokenValidity: 60

      AllowedOAuthFlows:
        - code
        - implicit

      AllowedOAuthFlowsUserPoolClient: true

      AllowedOAuthScopes:
        - openid
        - email

      DefaultRedirectURI: !Ref RedirectURL
      CallbackURLs:
        - !Ref RedirectURL
      LogoutURLs:
        - !Ref RedirectURL

      EnablePropagateAdditionalUserContextData: false
      EnableTokenRevocation: true
      GenerateSecret: true
      PreventUserExistenceErrors: ENABLED

      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH

      SupportedIdentityProviders:
        - COGNITO

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !GetAtt UserPoolClient.ClientId
          CLIENT_SECRET: !Ref ClientSecret
          REDIRECT_URI: !Ref RedirectURL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get

  FunctionCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !GetAtt UserPoolClient.ClientId
          CLIENT_SECRET: !Ref ClientSecret
          REDIRECT_URI: !Ref RedirectURL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /callback
            Method: get

  FunctionDashboard:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !GetAtt UserPoolClient.ClientId
          CLIENT_SECRET: !Ref ClientSecret
          REDIRECT_URI: !Ref RedirectURL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dashboard
            Method: get

  FunctionLogout:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !GetAtt UserPoolClient.ClientId
          CLIENT_SECRET: !Ref ClientSecret
          REDIRECT_URI: !Ref RedirectURL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /logout
            Method: get

  FunctionPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !GetAtt UserPoolClient.ClientId
          CLIENT_SECRET: !Ref ClientSecret
          REDIRECT_URI: !Ref RedirectURL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /post
            Method: post

Outputs:
  Placeholder:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Ref Placeholder

  Main:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  RedirectURI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/callback"

  ClientId:
    Description: "ClientId"
    Value: !Sub ${UserPoolClient.ClientId}

  ClientSecret:
    Description: "User Pool Information"
    Value: !Sub ${UserPool.ProviderURL}

  UserPoolClientAppURL:
    Description: "User Pool Client App URL"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cognito/v2/idp/user-pools/${UserPool}/app-integration/clients/${UserPoolClient.ClientId}?region=us-east-1"

  CognitoHostedURL:
    Description: "Cognito Hosted URL"
    Value: !Sub "https://${Domain}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize?client_id=${UserPoolClient.ClientId}&response_type=code&scope=email+openid&redirect_uri=https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/callback"
