AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: flightsim

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  FlightSimFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code
      Handler: fast.handler
      Runtime: python3.14
      MemorySize: 256
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: HttpApi # More info about HttpApi Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessHttpApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#httpapi
  FlightSimApi:
    Description: "HTTP API Gateway endpoint URL for Flight Sim"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  FlightSimFunction:
    Description: "Flight Sim Lambda Function ARN"
    Value: !GetAtt FlightSimFunction.Arn
  FlightSimFunctionIamRole:
    Description: "Implicit IAM Role created for Flight Sim function"
    Value: !GetAtt FlightSimFunctionRole.Arn
