AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hlb-mailtrap-s3-develop

Parameters:
  Environment:
    Description: Environment to deploy to
    Type: String

  CloudfrontDomain:
    Description: Environment to deploy to
    Type: String

  ProtectedIP:
    Description: Environment to deploy to
    Type: String

  FormImage:
    Description: Environment to deploy to
    Type: String

  ExpireS3:
    Description: Days to Expire S3
    Type: String

  CachePolicy:
    Description: Days to Cache in Cloudfront
    Type: Number
    Default: 2592000 # 30 days

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "hlb-mailtrap-s3-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldInput
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref ExpireS3
            Prefix: input/
          - Id: ExpireOldCDN
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref ExpireS3
            Prefix: cdn/

  Table:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-s3-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  Function:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: code
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Sub "hlb-mailtrap-s3-${Environment}"
          CLOUDFRONT_URL: !Ref CloudfrontDomain
          TABLE: !Ref Table
          PROTECTED_IP: !Ref ProtectedIP
          FORM_IMAGE: !Ref FormImage
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "hlb-mailtrap-s3-${Environment}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: input/
  FunctionWebsite:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: code
      Handler: website.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Sub "hlb-mailtrap-s3-${Environment}"
          CLOUDFRONT_URL: !Ref CloudfrontDomain
          TABLE: !Ref Table
          PROTECTED_IP: !Ref ProtectedIP
          FORM_IMAGE: !Ref FormImage
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  CloudfrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "hlb-mailtrap-s3-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Enabled: 'true'

        CacheBehaviors:
          - CachePolicyId: !Ref CloudfrontCachePolicy
            PathPattern: '*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https

        Origins: 
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig: 
              OriginAccessIdentity: ''
            OriginAccessControlId: EPVXFKJZGSO2D

        DefaultCacheBehavior: 
          TargetOriginId: S3Origin
          ForwardedValues: 
            QueryString: 'false'
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Comment: Cloudfront distribution for hlb-mailtrap-s3
        PriceClass: PriceClass_100

  CloudfrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "hlb-mailtrap-s3-${Environment}"
        DefaultTTL: !Ref CachePolicy
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: none

Outputs:
  CloudfrontDomain:
    Value: !GetAtt Cloudfront.DomainName
    Description: The domain name of the Cloudfront distribution

  Website:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
