AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hlb-mailtrap-s3-develop

Parameters:
  Environment:
    Description: Environment to deploy to
    Type: String
    AllowedValues:
      - prod
      - develop

  CloudfrontDomain:
    Description: Cloudfront Domain
    Type: String

  ProtectedIP:
    Description: Protect IP for Emails
    Type: String

  Email:
    Description: Protect IP for Emails
    Type: String

  FormImage:
    Description: Image for Form Completion
    Type: String

  ExpireS3:
    Description: Days to Expire S3
    Type: String

  CachePolicy:
    Description: Days to Cache in Cloudfront
    Type: Number
    Default: 2592000 # 30 days

  PythonRuntime:
    Description: Python Runtime for the Lambda Function
    Type: String
    Default: python3.14
    AllowedValues:
      - python3.10
      - python3.14

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "hlb-mailtrap-s3-${Environment}"
      TopicName: !Sub "hlb-mailtrap-s3-${Environment}"

  Subscription:
    Type: AWS::SNS::Subscription
    Condition: IsProduction
    Properties:
      Protocol: email
      TopicArn: !Ref Topic
      Endpoint: !Ref Email

  Bucket:
    Type: AWS::S3::Bucket
    Condition: IsProduction
    Properties:
      BucketName: !Sub "hlb-mailtrap-s3-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldInput
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref ExpireS3
            Prefix: input/
          - Id: ExpireOldCDN
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref ExpireS3
            Prefix: cdn/

  Table:
    Type: AWS::DynamoDB::Table
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-s3-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  TableArchive:
    Type: AWS::DynamoDB::Table
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-archive-${Environment}"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: order
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: order
          KeyType: RANGE

  TableVote:
    Type: AWS::DynamoDB::Table
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-vote-${Environment}"
      BillingMode: PAY_PER_REQUEST

      GlobalSecondaryIndexes:
        - IndexName: newsletter-index
          KeySchema:
            - AttributeName: newsletter
              KeyType: HASH
          Projection:
            ProjectionType: ALL

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      AttributeDefinitions:
        - AttributeName: newsletter
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
        - AttributeName: newsletter
          KeyType: RANGE

  TableUTM:
    Type: AWS::DynamoDB::Table
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-utm-${Environment}"
      BillingMode: PAY_PER_REQUEST

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH

  TablePosts:
    Type: AWS::DynamoDB::Table
    Condition: IsProduction
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "hlb-mailtrap-posts-${Environment}"
      BillingMode: PAY_PER_REQUEST

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      AttributeDefinitions:
        - AttributeName: cdn_photo
          AttributeType: S
        - AttributeName: csv
          AttributeType: S
      KeySchema:
        - AttributeName: csv
          KeyType: HASH
        - AttributeName: cdn_photo
          KeyType: RANGE

  Function:
    Type: AWS::Serverless::Function
    Condition: IsProduction
    Properties:
      CodeUri: code
      Handler: app.lambda_handler
      Runtime: !Ref PythonRuntime
      Timeout: 90
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Sub "hlb-mailtrap-s3-${Environment}"
          ENVIRONMENT: !Ref Environment
          CLOUDFRONT_URL: !Ref CloudfrontDomain
          TABLE: !Ref Table
          TABLE_ARCHIVE: !Ref TableArchive
          TABLE_VOTE: !Ref TableVote
          PROTECTED_IP: !Ref ProtectedIP
          FORM_IMAGE: !Ref FormImage
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "hlb-mailtrap-s3-${Environment}"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: input/
  FunctionWebsite:
    Type: AWS::Serverless::Function
    Condition: IsProduction
    Properties:
      CodeUri: code
      Handler: website.lambda_handler
      Runtime: !Ref PythonRuntime
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Sub "hlb-mailtrap-s3-${Environment}"
          ENVIRONMENT: !Ref Environment
          CLOUDFRONT_URL: !Ref CloudfrontDomain
          TABLE: !Ref Table
          TABLE_ARCHIVE: !Ref TableArchive
          TABLE_VOTE: !Ref TableVote
          TABLE_UTM: !Ref TableUTM
          TABLE_Posts: !Ref TablePosts
          PROTECTED_IP: !Ref ProtectedIP
          FORM_IMAGE: !Ref FormImage
          TOPIC: !Ref Topic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - DynamoDBCrudPolicy:
            TableName: !Ref TableArchive
        - DynamoDBCrudPolicy:
            TableName: !Ref TableVote
        - DynamoDBCrudPolicy:
            TableName: !Ref TableUTM
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt Topic.TopicName
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Newsletter:
          Type: HttpApi
          Properties:
            Path: /newsletter/{proxy+}
            Method: ANY

  CloudfrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Condition: IsProduction
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "hlb-mailtrap-s3-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Condition: IsProduction
    Properties:
      DistributionConfig:
        Enabled: 'true'

        CacheBehaviors:
          - CachePolicyId: !Ref CloudfrontCachePolicy
            PathPattern: '*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https

        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudfrontOriginAccessControl

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Comment: Cloudfront distribution for hlb-mailtrap-s3
        PriceClass: PriceClass_100

  CloudfrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Condition: IsProduction
    Properties:
      CachePolicyConfig:
        Name: !Sub "hlb-mailtrap-s3-${Environment}"
        DefaultTTL: !Ref CachePolicy
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

Outputs:
  CloudfrontDomain:
    Condition: IsProduction
    Value: !GetAtt Cloudfront.DomainName
    Description: The domain name of the Cloudfront distribution

  Website:
    Condition: IsProduction
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"