AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 256
    Architectures:
      - x86_64

Resources:
  ytdlp:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: hlb-yt-dlp
      Description: hlb-yt-dlp
      ContentUri: ../../layers/yt-dlp
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  Function:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11