version = 0.1
[default.deploy.parameters]
stack_name = "hlb-jane-cat-photos"
resolve_s3 = true
s3_prefix = "hlb-jane-cat-photos"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExpireS3=\"15\" CachePolicy=\"2592000\""
image_repositories = []
