AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hlb-jane-cat-photos

Parameters:
  ExpireS3:
    Description: Days to Expire S3
    Type: Number
    Default: 15

  CachePolicy:
    Description: Days to Cache in Cloudfront
    Type: Number
    Default: 2592000 # 30 days

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "hlb-jane-cat-photos"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldPhotos
            Status: Enabled
            NoncurrentVersionExpirationInDays: !Ref ExpireS3
            Prefix: photos/

  CloudfrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "hlb-jane-cat-photos"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        Enabled: 'true'

        CacheBehaviors:
          - CachePolicyId: !Ref CloudfrontCachePolicy
            PathPattern: '*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https

        Origins: 
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig: 
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudfrontOriginAccessControl

        DefaultCacheBehavior: 
          TargetOriginId: S3Origin
          ForwardedValues: 
            QueryString: 'false'
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Comment: Cloudfront distribution for jane-cat-photos
        PriceClass: PriceClass_100

  CloudfrontCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: jane-cat-photos
        DefaultTTL: !Ref CachePolicy
        MinTTL: 0
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: none

Outputs:
  CloudfrontDomain:
    Value: !GetAtt Cloudfront.DomainName
    Description: The domain name of the Cloudfront distribution

  BucketName:
    Value: !Ref Bucket
    Description: The bucket name

