version = 0.1
[default.deploy.parameters]
stack_name = "hlb-email-list"
resolve_s3 = true
s3_prefix = "hlb-email-list"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Email=\"kevin@homelabwithkevin.com\""
image_repositories = []
