AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "hlb-email-list"

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  Email:
    Type: String

Resources:
  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref Email
