services:
  rocketchat:
    image: rocket.chat:7.3
    restart: always
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      ROOT_URL: http://localhost:3000
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    ports:
      - 3000:3000

  mongodb:
    image: quay.io/flakybitnet/mongodb-server:7.0.16-fb2
    restart: always
    volumes:
      - ./mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      ALLOW_EMPTY_PASSWORD: 'true'
