name: Deploy to Amazon via AWS SAM

on:
  push:
    branches: [ "main", "**"]

env:
  AWS_REGION: us-east-2
  ROLE_TO_ASSUME: arn:aws:iam::195663387853:role/playground-sam-gh
  WORKING_DIRECTORY: aws-roles/sam/playground-sam-role

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: aws-roles/sam/playground-sam-role

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: true

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      if: true
      with:
        python-version: "3.11"
    
    - name: Setup SAM
      uses: aws-actions/setup-sam@v2
      if: true
      with:
        use-installer: true

    - name: Install dependencies
      if: false
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: true
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}

    - name: AWS SAM Build
      if: true
      run: |
        sam build

    - name: AWS SAM Deploy
      if: true
      run: |
        cd ${{ env.WORKING_DIRECTORY }} && sam deploy