name: yt-dlp - Deploy to AWS

on:
  # push:
  #   branches: [ "main", "yt-dlp/**" ]
  schedule:
     - cron: "0 16 * * *"

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: yt-dlp/aws

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IAM_ROLE }}

    - name: Install CDK
      run: npm install -g aws-cdk   

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.11

    - name: Install CDK
      run: pip install aws-cdk-lib
            
    - name: CDK Synth
      if: false
      run: cdk synth

    - name: CDK Deploy
      run: cdk deploy --require-approval never
