name: yt-dlp - Deploy to AWS via AWS SAM

on:
  push:
    branches: [ "main", "**"]
    # paths:
    #   - yt-dlp/sam

  schedule:
     - cron: "0 16 * * *"

  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: ./yt-dlp/aws/sam

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: true

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      if: true
      with:
        python-version: "3.11"

    - name: Setup SAM
      uses: aws-actions/setup-sam@v2
      if: true
      with:
        use-installer: true

    - name: Install dependencies
      if: false
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: true
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}

    - name: AWS SAM Build
      if: true
      run: |
        sam build

    - name: AWS SAM Deploy
      if: false
      run: |
        sam deploy
