name: yt-dlp - Deploy to AWS

on:
  push:
    branches: [ "main", "yt-dlp/**" ]

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working_directory: yt-dlp/aws

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::654654599343:role/github-oidc-Role-D3eCEyNBMTFo

    - name: Install CDK
      run: npm install -g aws-cdk   

    - name: CDK Synth
      run: cdk synth
